export const categories = [
  ["Chicken", "chicken", "Spicy campus favorites with crispy, saucy, and biryani picks.", "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80"],
  ["Mutton", "mutton", "Rich slow-cooked plates for serious lunch breaks.", "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80"],
  ["Veg Meals", "veg-meals", "Balanced vegetarian thalis and comfort meals.", "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=900&q=80"],
  ["Biryani", "biryani", "Aromatic rice bowls built for hungry study sessions.", "https://images.unsplash.com/photo-1631515242808-497c3fbd3972?auto=format&fit=crop&w=900&q=80"],
  ["Noodles", "noodles", "Hot wok noodles with fast prep and bold sauces.", "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80"],
  ["Fried Rice", "fried-rice", "Smoky fried rice bowls with veg, egg, and chicken options.", "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80"],
  ["Breakfast", "breakfast", "Morning fuel before labs, lectures, and exams.", "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=80"],
  ["Snacks", "snacks", "Quick bites, crispy sides, and evening cravings.", "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80"],
  ["Soft Drinks", "soft-drinks", "Classic bottled refreshers chilled for delivery.", "https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=900&q=80"],
  ["Cool Drinks", "cool-drinks", "Cold campus coolers, shakes, and mocktails.", "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80"],
  ["Ice Creams", "ice-creams", "Scoops, sundaes, and late-night dessert breaks.", "https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?auto=format&fit=crop&w=900&q=80"],
  ["Juices", "juices", "Fresh fruit juices for a lighter recharge.", "https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80"],
  ["Tea & Coffee", "tea-coffee", "Hot sips for assignments, breaks, and all-nighters.", "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"],
  ["Burgers", "burgers", "Stacked buns with crisp patties and creamy sauces.", "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80"],
  ["Sandwiches", "sandwiches", "Grilled and fresh sandwiches for quick meals.", "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80"],
  ["Rolls", "rolls", "Wrapped meals with spicy fillings and soft parathas.", "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80"],
  ["South Indian", "south-indian", "Dosa, idli, vada, and sambar classics.", "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=900&q=80"],
  ["North Indian", "north-indian", "Paneer, dal, roti, and curry comfort plates.", "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=80"],
  ["Desserts", "desserts", "Sweet finishes from cakes to gulab jamun.", "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80"],
  ["Combo Offers", "combo-offers", "Value bundles for groups, roommates, and big appetites.", "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80"],
];

export const foodNames = {
  chicken: ["Chicken Manchurian", "Chicken Noodles", "Chicken Fried Rice", "Chicken Biryani", "Chicken Roll", "Chicken 65"],
  mutton: ["Mutton Curry", "Mutton Biryani", "Mutton Fry", "Mutton Keema", "Mutton Fried Rice", "Mutton Soup"],
  "veg-meals": ["Veg Thali", "Curd Rice", "Lemon Rice", "Tomato Rice", "Chapati Curry", "Veg Pulao"],
  biryani: ["Veg Biryani", "Egg Biryani", "Chicken Dum Biryani", "Mutton Dum Biryani", "Paneer Biryani", "Family Biryani Bowl"],
  noodles: ["Veg Noodles", "Egg Noodles", "Schezwan Noodles", "Chicken Noodles", "Paneer Noodles", "Triple Noodles"],
  "fried-rice": ["Veg Fried Rice", "Egg Fried Rice", "Chicken Fried Rice", "Schezwan Fried Rice", "Paneer Fried Rice", "Mixed Fried Rice"],
  breakfast: ["Idli Sambar", "Masala Dosa", "Poori Masala", "Aloo Paratha", "Bread Omelette", "Upma Bowl"],
  snacks: ["Samosa", "Puffs", "French Fries", "Chilli Potato", "Paneer Pakoda", "Masala Maggi"],
  "soft-drinks": ["Coke", "Pepsi", "Sprite", "Thums Up", "Fanta", "Soda Lime"],
  "cool-drinks": ["Cold Coffee", "Lassi", "Rose Milk", "Lemon Mint Cooler", "Chocolate Shake", "Mango Shake"],
  "ice-creams": ["Vanilla Scoop", "Chocolate Scoop", "Butterscotch Cup", "Strawberry Sundae", "Brownie Ice Cream", "Kulfi Stick"],
  juices: ["Orange Juice", "Watermelon Juice", "Pineapple Juice", "Mango Juice", "Apple Juice", "Mixed Fruit Juice"],
  "tea-coffee": ["Masala Tea", "Ginger Tea", "Filter Coffee", "Cappuccino", "Black Coffee", "Hot Chocolate"],
  burgers: ["Veg Burger", "Cheese Burger", "Chicken Burger", "Paneer Burger", "Double Patty Burger", "Crispy Burger"],
  sandwiches: ["Veg Grilled Sandwich", "Cheese Corn Sandwich", "Chicken Sandwich", "Paneer Tikka Sandwich", "Club Sandwich", "Chocolate Sandwich"],
  rolls: ["Veg Roll", "Egg Roll", "Chicken Roll", "Paneer Roll", "Double Egg Roll", "Cheese Chicken Roll"],
  "south-indian": ["Plain Dosa", "Onion Dosa", "Medu Vada", "Ghee Podi Idli", "Uttapam", "Pongal"],
  "north-indian": ["Paneer Butter Masala", "Dal Tadka", "Chole Bhature", "Butter Naan", "Rajma Chawal", "Aloo Jeera"],
  desserts: ["Gulab Jamun", "Rasmalai", "Chocolate Brownie", "Cheesecake Cup", "Fruit Custard", "Caramel Pudding"],
  "combo-offers": ["Burger Fries Combo", "Biryani Coke Combo", "Dosa Coffee Combo", "Noodles Manchurian Combo", "Thali Sweet Combo", "Roommates Mega Combo"],
};
